spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    # 此配置仅在MemberBrandAttention、MemberProductCollection、MemberReadHistory中及其对应的'*Repository'中使用，
      # 这部分对外的服务，主要是用户关注、收藏、浏览历史。
    mongodb:
      host: 127.0.0.1
      port: 9299 #27017
      database: mall-portal

  redis:
    host: localhost # Redis服务器地址
    database: 9 # Redis数据库索引（默认为0）
    port: 8379 # Redis服务器连接端口（默认6379）
    password: 123456 # Redis服务器连接密码（默认为空，则不填）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq: # 用于实现延时取消未支付的订单（二开时废弃）
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug

